### PR TITLE
Fix connection restoration bug

### LINKED ISSUE #228: Prior CF connections restored despite access token loss
Currently, a TAS connection from a previous VS session can be restored (re-displayed in TAS Explorer window using info saved in VS store) even when the access token used to interact with that environment can no longer be found. 

This results in a connection displayed in the TAS Explorer that looks usable but which throws an error when attempts are made to expand (get orgs for) it:

If the access token does not persist across VS sessions, neither should the CF connection as displayed in the TAS Explorer window.

_Note:_ this may only be an issue for experimental instances of Visual Studio; the `.cf` directory that records the access token doesn't seem to lose data between sessions of a "real" VS instance.

### PR DESCRIPTION
**Pull request by atwoosnam**
Fixes #228 -- connection no longer restored when access token irretrievable:

persistent-connection-bug-fix

### CODE REVIEW

File: src/Services/src/CloudFoundry/CloudFoundryService.cs [hunk 1]
```diff
@@ -995,6 +995,20 @@ public async Task<DetailedResult<List<string>>> GetStackNamesAsync(CloudFoundryI
             };
         }
 
+        /// <summary>
+        /// Attempts to retrieve cached access token
+        /// </summary>
+        /// <returns>
+        /// True if token is accessible & appears valid.
```
Comment (ccheetham) [inline src/Services/src/CloudFoundry/CloudFoundryService.cs:1002]: prefer "and" over symbol

File: src/Services/src/CloudFoundry/ICloudFoundryService.cs [hunk 2]
```diff
@@ -22,5 +22,6 @@ public interface ICloudFoundryService
         Task<DetailedResult<List<string>>> GetStackNamesAsync(CloudFoundryInstance cf, int retryAmount = 1);
         Task<DetailedResult<string>> GetSsoPrompt(string cfApiAddress);
         Task<DetailedResult> LoginWithSsoPasscode(string cfApiAddress, string passcode);
+        bool ValidateConnection();
```
Comment (ccheetham) [inline src/Services/src/CloudFoundry/ICloudFoundryService.cs:25]:
```suggestion
        bool IsValidConnection();
```

**Review by ccheetham — CHANGES_REQUESTED** [review]

File: src/Services/src/CloudFoundry/CloudFoundryService.cs (hunk 1 above)
Comment (atwoosnam) [reply src/Services/src/CloudFoundry/CloudFoundryService.cs]: Fixed in b60fa23

File: src/Services/src/CloudFoundry/ICloudFoundryService.cs (hunk 2 above)
Comment (atwoosnam) [reply src/Services/src/CloudFoundry/ICloudFoundryService.cs]: Fixed in b60fa23

**Review by ccheetham — APPROVED** [review]
lgtm
